In [8]:
#retation******************
import numpy as np
Rot = lambda theta: [[np.cos(theta), -np.sin(theta)],
[np.sin(theta), np.cos(theta)]]
R = Rot(np.pi/2)# here the angle **************************
R

#create a list of 2-D points
points =np.array([[0.25,1.5]])#here******************
#Now rotate them
rpoints = np.array([R @ p for p in points])
#Show the two sets of points
print(R)
print("****************")
print(rpoints)

[[6.123233995736766e-17, -1.0], [1.0, 6.123233995736766e-17]]
****************
[[-1.5   0.25]]


In [4]:
#refluction*************
import numpy as np
Rot = lambda theta: [[np.cos(2*theta), np.sin(2*theta)],
[np.sin(2*theta), -np.cos(2*theta)]]
R = Rot(np.pi/4)# here the angle **************************
R
#create a list of 2-D points
points =np.array([[0.25,1.5]])#here******************
#Now rotate them
rpoints = np.array([R @ p for p in points])
#Show the two sets of points
print(R)
print("****************")
print(rpoints)

[[6.123233995736766e-17, 1.0], [1.0, -6.123233995736766e-17]]
****************
[[1.5  0.25]]


In [ ]:
#projection
import numpy as np
Rot = lambda theta: [[(1/2)*(1+np.cos(2*theta)), (1/2)*np.sin(2*theta)],
[(1/2)*np.sin(2*theta), (1/2)*(1-np.cos(theta))]]
R = Rot(np.pi/3)# here the angle **************************
R

#create a list of 2-D points
points =np.array([[1,0],[ 1.5,0],[2,0],[1,0.25],[1.5,0.25],[1,0.5]])#here******************
#Now rotate them
rpoints = np.array([R @ p for p in points])
#Show the two sets of points
print(R)
print("****************")
print(rpoints)

In [5]:
#dilation***********
import numpy as np
dilt = lambda x,y: np.array([[x, 0],[0, y]])

D= dilt(0.25, 1.5) # put here the dilation matrix
x=np.array([0.25, 3]) # write the vector required
D@x


array([0.0625, 4.5   ])

In [24]:
#reverse
reverser = lambda n: np.flip(np.eye(n),axis=0)
A = reverser(3)# but here the size of the vector u have 
x=np.array([1,2,3])#size of this
A@ x

array([3., 2., 1.])

In [21]:
A = np.array([[0,0,1], [1,0,0], [0,1,0]])#**************
x = np.array([0.2, -1.7, 2.4])#*****************
A @ x # Permutes entries of x to [x[2], x[0], x[1]]

array([ 2.4,  0.2, -1.7])

In [30]:
#networling 

#circulation
A = np.array([[-1,-1,0,1,0], [1,0,-1,0,0], [0,0,1,-1,-1], [0,1,0,0,1]])# here*****************
xcirc = np.array([1,-1,1,0,1]) #A circulation given as x
A @ xcirc
#******************
#for sorce points
s = np.array([1,0,-1,0,]) # A source vector 
x = np.array([0.6,0.3,0.6,-0.1,-0.3]) #A flow vector
A @ x + s #Total incoming flow at each node
print(A @ xcirc)
print("***********")
print(A @ x + s)

[0 0 0 0]
***********
[1.11022302e-16 0.00000000e+00 0.00000000e+00 0.00000000e+00]


In [11]:
#for smoth ******************
A = np.array([[-1,-1,0,1,0], [1,0,-1,0,0], [0,0,1,-1,-1], [0,1,0,0,1]])
vsmooth = np.array([1,2,0,1])
np.linalg.norm(A.T @ vsmooth)**2

7.000000000000001

In [9]:
#conloution***************
b = np.array([-5,2,3])
a = np.array([5,3,-1,1])
print(np.convolve(a,b))


[-25  -5  26   2  -1   3]


In [10]:
#Permutation matrix*****************
import numpy as np

A = np.array([[0,0,1], [1,0,0], [0,1,0]])# Permutation matrix
x = np.array([[0.66,0.66,0.03],[0.03,0.65,0.93],[0.03,0.33,0.78]])# the maxrix of vector required

A @ x # Permutes entries of x to [x[2], x[0], x[1]]

array([[0.03, 0.33, 0.78],
       [0.66, 0.66, 0.03],
       [0.03, 0.65, 0.93]])