In [32]:
import numpy as np
x=np.array([[-2,7],[3,6]])
np.linalg.inv(x)

array([[-0.18181818,  0.21212121],
       [ 0.09090909,  0.06060606]])

In [50]:
A = np.array([[1,-3, 7], [-1,4,-6], [1,4,6],[1,-3,0]])######change
b=np.array([3,0,3,1])######change
Q,R =np.linalg.qr(A)
print(np.linalg.inv(R)@(Q.T)@b)


[1.4792445  0.23225405 0.13034454]


In [26]:
A = np.array([[1,-3, 7], [-1,4,-6], [1,4,6],[1,-3,0]])######change


1.0

array([[-1., -1.],
       [ 0., -2.]])

array([[ 1.,  0.],
       [-0.,  1.]])

array([[-1. ,  0.5],
       [-0. , -0.5]])