In [4]:
import numpy as np
A=np.array([[12,55],[56,87]])
np.linalg.qr(A)

(array([[-0.20952909, -0.97780241],
        [-0.97780241,  0.20952909]]),
 array([[-57.27128425, -96.5929099 ],
        [  0.        , -35.55010205]]))

In [6]:
B = np.linalg.inv(A)
B

array([[-0.04273084,  0.02701375],
       [ 0.02750491, -0.00589391]])

In [9]:
B = np.linalg.pinv(A)
B

array([[-0.04273084,  0.02701375],
       [ 0.02750491, -0.00589391]])