In [5]:
import numpy as np
A = np.array([[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]])
A.shape

(3, 4)

In [7]:
m,n = A.shape
print("m:", m)
print("n:", n)

m: 3
n: 4


In [8]:
tall = lambda X: A.shape[0] > A.shape[1]
tall(A)

False

In [13]:
A = np.array([[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]])
print("m:", len(A))
print("n:", len(A[0]))

m: 3
n: 4


In [14]:
A[0,2]

-2.3

In [15]:
A = np.array([[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]])
B = A.copy()
A == B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
B[0,3] = 100 
np.sum(A==B)

11

In [18]:
A = ([[0,1,-2.3,0.1],[1.3, 4, -0.1, 0],[4.1, -1.0, 0, 1.7]])
B =( [[0,1,-2.3,100],[1.3, 4, -0.1, 0],[4.1, -1.0, 0, 1.7]])
A == B

False

In [ ]:
a = np.array([-2.1, -3, 0])
a.shape

In [ ]:
b = np.array([[-2.1],[-3],[0]])
b.shape

In [ ]:
c = np.array([[-2.1, -3, 0]])
c.shape

In [19]:
A= np.array([[-1, 0, 1, 0],[2, -3, 0, 1],[0, 4, -2, 1]])
A[0:2, 2:4]

array([[1, 0],
       [0, 1]])

In [20]:
A[:,2]

array([ 1,  0, -2])

In [21]:
A[1,:]

array([ 2, -3,  0,  1])

In [22]:
A.reshape((6,2))

array([[-1,  0],
       [ 1,  0],
       [ 2, -3],
       [ 0,  1],
       [ 0,  4],
       [-2,  1]])

In [23]:
B = np.array([0,2,3]) #1 by 3 matrix
C = np.array([-1]) #1 by 1 matrix
D = np.array([[2,2,1],[1,3,5]]) #2 by 3 matrix
E = np.array([[4],[4]]) #2 by 1 matrix
# Constrcut 3 by 4 block matrix
49
A = np.block([[B,C],[D,E]])
A

array([[ 0,  2,  3, -1],
       [ 2,  2,  1,  4],
       [ 1,  3,  5,  4]])

In [27]:
a= [1,2]
b = [4,5]
c = [7,8]
A = np.vstack([a,b,c])
B = np.hstack([a,b,c])
print("matrix A :",A)
print("dimensions of A :", A.shape)
print("matrix B :",B)
print("dimensions of B :", B.shape)


matrix A : [[1 2]
 [4 5]
 [7 8]]
dimensions of A : (3, 2)
matrix B : [1 2 4 5 7 8]
dimensions of B : (6,)


In [28]:
np.c_[-np.identity(3), np.zeros(3)]

array([[-1., -0., -0.,  0.],
       [-0., -1., -0.,  0.],
       [-0., -0., -1.,  0.]])

In [29]:
np.r_[np.identity(3), np.zeros((1,3))]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [30]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
x = np.array([[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])
print(np.diag(x))

[0 4 8]


In [35]:
from scipy import sparse
diagonals = np.array([[1, 2, 3, 4], [1, 2, 3], [1, 2]])
B = sparse.diags(diagonals, offsets=[0,-1,2])
B.todense()

<ipython-input-35-67a4fa7327aa>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  diagonals = np.array([[1, 2, 3, 4], [1, 2, 3], [1, 2]])


matrix([[1., 0., 1., 0.],
        [1., 2., 0., 2.],
        [0., 2., 3., 0.],
        [0., 0., 3., 4.]])