In [3]:
#NPV
import numpy as np
r = 0.05
e1 = np.array([1,0,0])
l1 = np.array([1, -(1+r), 0])
l2 = np.array([0,1,-(1+r)])
c = np.array([1,2,-3])
# Coefficients of expansion
alpha3 = -c[2]/(1+r)
alpha2 = -c[1]/(1+r) - c[2]/((1+r)**2)
alpha1 = c[0] + c[1]/(1+r) + c[2]/((1+r)**2) #NPV of cash flow
print(alpha1)

0.18367346938775508


In [4]:
import numpy as np
a1 = np.array([0,0,-1])
a2 = np.array([1,1,0])/(2)**0.5
a3 = np.array([1,-1,0])/(2)**0.5
print("Norm of a1 :", (sum(a1**2))**0.5)
print("Norm of a2 :", (sum(a2**2))**0.5)
print("Norm of a3 :", (sum(a3**2))**0.5)
print(a1 @ a2, a1 @ a3, a2 @ a3)
x= np.array([1,2,3])
#Get coefficients of x in orthonormal basis
beta1 = a1 @ x
beta2 = a2 @ x
beta3 = a3 @ x
#Expansion of x in basis
x_expansion = beta1*a1 + beta2*a2 + beta3*a3
print(x_expansion)

Norm of a1 : 1.0
Norm of a2 : 0.9999999999999999
Norm of a3 : 0.9999999999999999
0.0 0.0 0.0
[1. 2. 3.]


In [4]:
#gram
import numpy as np
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
        #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q
q = np.array([[1, -1, 1, -1], [1, 1, 3, -1], and v3= (-3, 7, 1, 3)])#here
print(gram_schmidt(q), "\n")

#Test orthonormality
print('Norm of q[0] :', (sum(q[0]**2))**0.5, "\n")
print('Inner product of q[0] and q[1] :', q[0] @ q[1], "\n")
print('Inner product of q[0] and q[2] :', q[0] @ q[2], "\n")
print('Norm of q[1] :', (sum(q[1]**2))**0.5, "\n")
print('Inner product of q[1] and q[2] :', q[1] @ q[2], "\n")
print('Norm of q[2] :', (sum(q[2]**2))**0.5, "\n")

Vectors are linearly independent.
[array([ 0.37796447, -0.75592895,  0.37796447, -0.37796447]), array([ 0.17457431,  0.56736651,  0.7855844 , -0.17457431]), array([-0.57154761, -0.32659863,  0.48989795,  0.57154761])] 

Norm of q[0] : 2.6457513110645907 

Inner product of q[0] and q[1] : 3 

Inner product of q[0] and q[2] : -19 

Norm of q[1] : 3.4641016151377544 

Inner product of q[1] and q[2] : 4 

Norm of q[2] : 8.246211251235321 



In [2]:
#k -means
import numpy as np
def group_assignment(data,centroids):
    grouping_vec_c = np.zeros(len(data))
    for i in range(len(data)):
        dist = np.zeros(len(centroids))
        for j in range(len(centroids)):
            dist[j] = np.linalg.norm(data[i] - centroids[j])
        min_dist = min(dist)
        for j in range(len(centroids)):
            if min_dist == dist[j]:
                grouping_vec_c[i] = j+1
    return grouping_vec_c

def update_centroid(data, grouping, centroids):
    new_centroids = [];
    for i in range(len(centroids)):
        cent = np.zeros(len(data[0]))
        count = 0
        for j in range(len(data)):
            if grouping[j] == (i+1):
                cent = cent+data[j]
                count += 1
        group_average = cent/count
        new_centroids.append(group_average)
    return new_centroids

def clustering_objective(data, grouping, centroids):
    J_obj = 0
    for i in range(len(data)):
        for j in range(len(centroids)):
            if grouping[i] == (j+1):
                J_obj += np.linalg.norm(data[i] - centroids[j])**2
    J_obj = J_obj/len(data)
    return J_obj


def Kmeans_alg(data, centroids):
    iteration = 0
    J_obj_vector = []
    Stop = False
    while Stop == False:
        grouping = group_assignment(data, centroids)
        new_centroids = update_centroid(data, grouping, centroids)
        J_obj = clustering_objective(data, grouping, new_centroids)
        J_obj_vector.append(J_obj)
        iteration += 1
        if np.linalg.norm(np.array(new_centroids) - np.array(centroids)) < 1e-6:
            Stop = True
        else:
            centroids = new_centroids
    return new_centroids, grouping, J_obj_vector, iteration
data=np.array([(0.5, 1.5, 2, 1),(1, 0.5,2, 0.5),(2, 1.5, 1.5, 1.5),(0.5, 1, 2, 2)])
c=np.array([(0.5, 1.5, 2, 1),(1, 0.5,2, 0.5),(2, 1.5, 1.5, 1.5)])
Kmeans_alg(data,c)

([array([0.5 , 1.25, 2.  , 1.5 ]),
  array([1. , 0.5, 2. , 0.5]),
  array([2. , 1.5, 1.5, 1.5])],
 array([1., 2., 3., 1.]),
 [0.15625000000000003, 0.15625000000000003],
 2)

In [ ]:
#cluster
from sklearn.cluster import KMeans
import numpy as np
kmeans = KMeans(n_clusters=4, random_state=0).fit(X)
labels = kmeans.labels_
group_representative = kmeans.cluster_centers_
J_clust = kmeans.inertia_
X=np.array([])
print(kmeans)
print(roup_representative)
print(J_clust)